// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Station struct {
	StationCd       int        `json:"stationCD"`
	LineName        *string    `json:"lineName"`
	StationName     string     `json:"stationName"`
	Address         *string    `json:"address"`
	BeforeStation   *Station   `json:"beforeStation"`
	AfterStation    *Station   `json:"afterStation"`
	TransferStation []*Station `json:"transferStation"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
