// Package models contains generated code for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// BeforeStation represents a row from 'public.before_station'.
type BeforeStation struct {
	StationCd             int    `json:"station_cd"`               // station_cd
	StationName           string `json:"station_name"`             // station_name
	StationGCd            int    `json:"station_g_cd"`             // station_g_cd
	Address               string `json:"address"`                  // address
	LineCd                int    `json:"line_cd"`                  // line_cd
	LineName              string `json:"line_name"`                // line_name
	BeforeStationLineCd   int    `json:"before_station_line_cd"`   // before_station_line_cd
	BeforeStationLineName string `json:"before_station_line_name"` // before_station_line_name
	BeforeStationCd       int    `json:"before_station_cd"`        // before_station_cd
	BeforeStationName     string `json:"before_station_name"`      // before_station_name
	BeforeStationAddress  string `json:"before_station_address"`   // before_station_address
}

// BeforeStationsByStationCD runs a custom query, returning results as BeforeStation.
func BeforeStationsByStationCD(ctx context.Context, db DB, stationCD int) ([]*BeforeStation, error) {
	// query
	const sqlstr = `select st2.station_cd, ` +
		`st2.station_name, ` +
		`st2.station_g_cd, ` +
		`st2.address, ` +
		`s2l.line_cd, ` +
		`s2l.line_name, ` +
		`COALESCE(s2l.line_cd, 0)     as before_station_line_cd, ` +
		`COALESCE(s2l.line_name, '')   as before_station_line_name, ` +
		`COALESCE(st2.station_cd, 0)   as before_station_cd, ` +
		`COALESCE(st2.station_name, '') as before_station_name, ` +
		`COALESCE(st2.address, '')      as before_station_address ` +
		` ` +
		`from station st ` +
		`inner join line li on st.line_cd = li.line_cd ` +
		`left outer join junction sjb on st.line_cd = sjb.line_cd and st.station_cd = sjb.station_cd2 ` +
		`left outer join junction sja on st.line_cd = sja.line_cd and st.station_cd = sja.station_cd1 ` +
		` ` +
		`left outer join station st2 on sjb.line_cd = st2.line_cd and sjb.station_cd1 = st2.station_cd ` +
		`left outer join line s2l on st2.line_cd = s2l.line_cd ` +
		`left outer join station st3 on sja.line_cd = st3.line_cd and sja.station_cd2 = st3.station_cd ` +
		` ` +
		`where st.station_cd = $1`
	// run
	logf(sqlstr, stationCD)
	rows, err := db.QueryContext(ctx, sqlstr, stationCD)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// load results
	var res []*BeforeStation
	for rows.Next() {
		var bs BeforeStation
		// scan
		if err := rows.Scan(&bs.StationCd, &bs.StationName, &bs.StationGCd, &bs.Address, &bs.LineCd, &bs.LineName, &bs.BeforeStationLineCd, &bs.BeforeStationLineName, &bs.BeforeStationCd, &bs.BeforeStationName, &bs.BeforeStationAddress); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &bs)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
