package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// StationByName represents a row from 'public.station_by_name'.
type StationByName struct {
	LineCd      int    `json:"line_cd"`      // line_cd
	LineName    string `json:"line_name"`    // line_name
	StationCd   int    `json:"station_cd"`   // station_cd
	StationGCd  int    `json:"station_g_cd"` // station_g_cd
	StationName string `json:"station_name"` // station_name
	Address     string `json:"address"`      // address
}

// StationByNamesByStationName runs a custom query, returning results as StationByName.
func StationByNamesByStationName(ctx context.Context, db DB, stationName int) ([]*StationByName, error) {
	// query
	const sqlstr = `select l.line_cd, l.line_name, s.station_cd, s.station_g_cd, s.station_name, s.address ` +
		`from station s ` +
		`inner join line l on s.line_cd = l.line_cd ` +
		`where s.station_name = $1 ` +
		`and s.e_status = 0`
	// run
	logf(sqlstr, stationName)
	rows, err := db.QueryContext(ctx, sqlstr, stationName)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// load results
	var res []*StationByName
	for rows.Next() {
		var sbn StationByName
		// scan
		if err := rows.Scan(&sbn.LineCd, &sbn.LineName, &sbn.StationCd, &sbn.StationGCd, &sbn.StationName, &sbn.Address); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &sbn)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
